name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - run: flutter pub get

      # Ensure CocoaPods is installed and the repo is updated
      - name: Install CocoaPods and update repository
        run: |
          brew install cocoapods || echo "CocoaPods already installed"
          pod repo update        # Update podspec repository
        working-directory: ios   # Run this inside the ios folder

      # Install pods for the iOS project
      - name: Install iOS Pods
        run: pod install --repo-update
        working-directory: ios   # Run this inside the ios folder

      # Build the iOS app
      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      # Create the Payload folder for IPA
      - name: Create Payload Folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      # Move the app into the Payload folder
      - name: Move App to Payload Folder
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Zip the payload into an IPA file
      - name: Zip output to IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload the IPA file as a release artifact
      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
