name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v3
        with:
          channel: 'stable'
          architecture: x64

      - name: Install CocoaPods (optional)
        run: brew install cocoapods
        if: 'needs cocoapods'

      - name: Get Flutter dependencies
        uses: actions/cache@v3
        with:
          path: pubspec.lock
          key: ${{ runner.os }}-lock-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-lock-
        if: 'needs flutter'

      - run: flutter pub get

      # Build the iOS app bundle
      - run: flutter build appbundle --release --no-codesign

      # Convert app bundle to IPA (adjust based on your chosen method)
      - name: Convert app bundle to IPA using flutter_build_ios_framework
        uses: flutter-framework/flutter-build-ios-framework@v1.0.0
        with:
          app_bundle: build/ios/release/app.aab
          output_directory: build/ios/iphoneos

      # Alternatively, use a script or tool to convert app bundle to IPA

      # Zip the IPA file
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload the IPA file as a release artifact
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"